name: ECS Service Deployment 
permissions:
  contents: read
  pull-requests: read
  
on:
  workflow_dispatch:

  push:
    branches:
      - development
      - staging
      - main

jobs:
  using_ecs:
    name: Reusing ECS Workflow
    uses: Traxi-on/reusable-workflows/.github/workflows/ecs.yml@main
    secrets: inherit
